version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: servicerate-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: servicerate
    ports:
      - "5432:5432"
    volumes:
      - servicerate_pgdata:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d

volumes:
  servicerate_pgdata: