spring.application.name=ServiceRateBackend

# PostgreSQL Datenbank Verbindung
spring.datasource.url=jdbc:postgresql://localhost:5432/servicerate
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate DDL Auto (Erstellt die 4 Tabellen automatisch)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true