spring.application.name=ServiceRateBackend
server.port=${SERVER_PORT:8081}

# PostgreSQL Datenbank Verbindung
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/servicerate}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# Hibernate DDL Auto (Erstellt die 4 Tabellen automatisch)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Externe APIs
openweather.api-key=${OPENWEATHER_API_KEY:}
